<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="1814" started-at="2021-11-04T09:55:18 AEDT" finished-at="2021-11-04T09:55:20 AEDT">
    <groups>
    </groups>
    <test name="DeleteCustomerTest" duration-ms="1814" started-at="2021-11-04T09:55:18 AEDT" finished-at="2021-11-04T09:55:20 AEDT">
      <class name="com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest@2805d709]" name="setUp" is-config="true" duration-ms="397" started-at="2021-11-04T09:55:17 AEDT" finished-at="2021-11-04T09:55:18 AEDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="DeleteCustomer(java.util.Hashtable)[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest@2805d709]" name="DeleteCustomer" duration-ms="1767" started-at="2021-11-04T09:55:18 AEDT" data-provider="data" finished-at="2021-11-04T09:55:20 AEDT">
          <params>
            <param index="0">
              <value>
                <![CDATA[{Runmode=Y, id=cus_KWfY6NGkOfIGqY}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [200] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:917)
at com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest.DeleteCustomer(DeleteCustomerTest.java:50)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:77)
at org.testng.internal.TestMethodWithDataProviderMethodWorker.call(TestMethodWithDataProviderMethodWorker.java:15)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteCustomer -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest@2805d709]" name="tearDown" is-config="true" duration-ms="0" started-at="2021-11-04T09:55:20 AEDT" finished-at="2021-11-04T09:55:20 AEDT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.automation.APIautomationFramework.testcases.Stripe.DeleteCustomerTest -->
    </test> <!-- DeleteCustomerTest -->
  </suite> <!-- Suite -->
</testng-results>
